import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner";
import { Roboto, Source_Code_Pro } from "next/font/google";
import "./globals.css";

// Define fonts with their respective CSS variables
const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "700"], // Add specific weights if needed
});

const sourceCodePro = Source_Code_Pro({
  variable: "--font-source-code-pro",
  subsets: ["latin"],
  weight: ["400", "700"], // Add specific weights if needed
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${sourceCodePro.variable} antialiased`}
      >
        <Toaster />
        {children}
      </body>
    </html>
  );
}
